name: Deploy Maven Application to EC2   
on:
  push:
    branches:
      - javatest2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '14'

    - name: Build with Maven
      run: mvn clean package



    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Save Docker image as tar
      run: docker save myapp:latest > myapp.tar

    - name: Transfer Docker image to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: myapp.tar
        target: /home/ubuntu/myapp.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          sudo docker load -i /home/ubuntu/myapp.tar/myapp.tar
          sudo docker run -dit --name myapp -p 8080:8080 myapp:latest
